library(dplyr)
library(chron)
dt <- read.csv2("household_power_consumption.txt", na.strings = "?")
dt <- mutate(dt,Date = strptime(dt$Date, format = "%d/%m/%Y"))
dt <- mutate(dt,Date = as.Date(dt$Date, format = "%d/%m/%Y"))
dt <- subset(dt, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
dates <- as.character(dt$Date)
times <- dt$Time
x <- paste(dates,times)
complete.dates <- strptime(x, "%Y-%m-%d %H:%M:%S")
dt <- mutate(dt, complete.dates = complete.dates)
dt <- group_by(dt,complete.dates)
png(filename = "plot2.png")
plot(dt$complete.dates, dt$Global_active_power, type = "l", xlab = "",ylab = "Global Active Power (kilowatts)")
dev.off()