library(dplyr)
library(chron)
dt <- read.csv2("household_power_consumption.txt", na.strings = "?")
dt <- mutate(dt,Date = strptime(dt$Date, format = "%d/%m/%Y"))
dt <- mutate(dt,Date = as.Date(dt$Date, format = "%d/%m/%Y"))
dt <- subset(dt, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
png(filename = "plot1.png")
hist(as.numeric(dt$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()