library(dplyr)
library(chron)
dt <- read.csv2("household_power_consumption.txt", na.strings = "?")
dt <- mutate(dt,Date = strptime(dt$Date, format = "%d/%m/%Y"))
dt <- mutate(dt,Date = as.Date(dt$Date, format = "%d/%m/%Y"))
dt <- subset(dt, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
dates <- as.character(dt$Date)
times <- dt$Time
x <- paste(dates,times)
complete.dates <- strptime(x, "%Y-%m-%d %H:%M:%S")
dt <- mutate(dt, complete.dates = complete.dates)
dt <- group_by(dt,complete.dates)
png(filename = "plot3.png")
with(dt,plot(complete.dates, Sub_metering_1, type = "n", xlab = "",ylab = "Energy sub metering"))
with(dt,points(complete.dates,Sub_metering_1, type = "l", col = "black"))
with(dt,points(complete.dates,Sub_metering_2, type = "l", col = "red"))
with(dt,points(complete.dates,Sub_metering_3, type = "l", col = "blue"))
legend("topright", lwd = 1 ,col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()